### ISSUE TITLE
attributes duplicated

### ISSUE THREAD

**Issue by nsheff** [databio/databio_genomes#3]
in this project, the file attributes are getting repeated for every merged attribute.

A bug has been introduced in peppy that messed up merging/deriving columns somewhere.
I think it may be related to this bug:

https://github.com/pepkit/peppy/issues/326

but not 100% sure.

Attributes assigned to a sample via constant attributes should not be duplicated for every subsample. I'm posting this issue here as an example, we'll have to rely on upstream changes to peppy before this project can work.

**Comment by stolarczyk** [comment]
https://github.com/pepkit/peppy/issues/328
