### ISSUE TITLE
server docs

### ISSUE THREAD

**Issue by nsheff** [databio/databio_genomes#4]
I'm a bit confused about the section 'Perparing to serve the assets'... can you clarify exactly what this is here? For example:

- what is a 'sample' in this PEP?
- what exactly is it doing?
- it seems to rely on a `pifaces` folder that is never specified; can you make it self-contained? for instance, the other pifaces for the build runs are located within this repo.
- can you add a README to the archive PEP subfolder?

to make the PEPs parallel, should we move the genomes PEP into a subfolder as well? maybe we should restructure this repo to:

archive_pep (PEP for archiver?)
assets_pep (PEP for assets)
pifaces (move all pifaces into a subfolder?)

**Comment by nsheff** [comment]
Thanks for changing the structure, but I still do not understand what the archives pep is for. There appears to only be 1 "sample" ('staging')... so why is this a PEP?

**Comment by nsheff** [comment]
maybe this is a 'server' PEP? Where each row is a server? I'm a bit confused by the naming, I think.

but each server is serving exactly the same thing, right? 

I still don't really understand why this is a PEP...

**Comment by stolarczyk** [comment]
> I still do not understand what the archives pep is for

The only reason why I made it a PEP is the convenience of submitting the `refgenieserver archive` job to the cluster. And yes, it always is going to be a single sample in there. 

that said, I'm aware that it can be confusing. We can take the whole section out and just say: 

"and now run this command: `refgenieserver archive ...`"

**Comment by nsheff** [comment]
I see. that's interesting. I think maybe you've found a use for divvy outside of looper... could you figure out a way to do this using divvy but not looper?

for example,

```
divvy write  --code 'refgenie server archive...' -o job.txt
sbatch job.txt
```

this leads to a new idea for divvy... we should just go ahead and write  `divvy submit`

```
divvy submit --code 'refgenie server archive...' --compute slurm
```
does that make sense?

**Comment by nsheff** [comment]
Actually, I forgot, you _can_ just do:

divvy write --code 'refgenie server archive...'

So the second point above is actually already possible...

**Comment by stolarczyk** [comment]
yes, that will be really useful. 

`write` command makes it pretty convenient already. I'll remove the PEP and update instructions to submit the job this way.
