### ISSUE TITLE
update to PEP spec 2

### ISSUE THREAD

**Issue by nsheff** [databio/databio_genomes#7]
Maybe a good test for pep 2.0?

**Comment by nsheff** [comment]
@stolarczyk looks great -- but needs a few more small tweaks for recent updates (`project_modifiers`)

**Comment by nsheff** [comment]
also update to latest looper (`looper run refgenie_build_cfg.yaml --compute local --sp getfiles` args now outdated)

**Comment by stolarczyk** [comment]
ok will do!

**Comment by stolarczyk** [comment]
should be resolved now.

btw, it feels both weird and awesome that it's possible to amend sample_modifiers from within project_modifiers

https://github.com/databio/databio_genomes/blob/80b3f93d4b3f4535c35ebeeab331dc0e639d6540/asset_pep/refgenie_build_cfg.yaml#L17-L24
